syntax = "proto3";

package zmk.macros;

import "keymap.proto";

message Request {
    oneof request_type {
        bool get_macro_state = 1;
        SetMacroRequest set_macro = 2;
        bool check_unsaved_changes = 3;
        bool save_changes = 4;
        bool discard_changes = 5;
        GetMacroRequest get_macro = 6;
        SetTapMsRequest set_tap_ms = 7;
        ResetMacroRequest reset_macro = 8;
    }
}

message Response {
    oneof response_type {
        MacroState get_macro_state = 1;
        SetMacroResponse set_macro = 2;
        bool check_unsaved_changes = 3;
        SaveChangesResponse save_changes = 4;
        bool discard_changes = 5;
        GetMacroResponse get_macro = 6;
        SetTapMsResponse set_tap_ms = 7;
        ResetMacroResponse reset_macro = 8;
    }
}

message Notification {
    oneof notification_type {
        MacroState macro_state_changed = 1;
        bool unsaved_changes_status_changed = 2;
    }
}

message MacroState {
    uint32 schema_version = 1;
    uint32 max_macros = 2;
    uint32 max_steps_per_macro = 3;
    repeated Macro macros = 4;
    bool dirty = 5;
    uint32 tap_ms = 6;
    uint32 pool_bytes_total = 7;
    uint32 pool_bytes_used = 8;
    uint32 max_macro_bytes = 9;
}

message Macro {
    uint32 slot_index = 1;
    sint32 behavior_id = 2;
    string name = 3;
    bool enabled = 4;
    repeated MacroStep steps = 5;
    bool dirty = 6;
    bytes packed_keys = 7;
    uint32 encoded_size = 8;
}

message MacroStep {
    MacroStepAction action = 1;
    zmk.keymap.BehaviorBinding binding = 2;
    uint32 wait_ms = 3;
    uint32 packed_keys_offset = 4;
    uint32 packed_keys_length = 5;
}

enum MacroStepAction {
    MACRO_STEP_ACTION_UNSPECIFIED = 0;
    MACRO_STEP_ACTION_TAP = 1;
    MACRO_STEP_ACTION_PRESS = 2;
    MACRO_STEP_ACTION_RELEASE = 3;
    MACRO_STEP_ACTION_WAIT = 4;
    MACRO_STEP_ACTION_TEXT = 5;
}

message GetMacroRequest {
    uint32 slot_index = 1;
}

message GetMacroResponse {
    Macro macro = 1;
}

message SetMacroRequest {
    Macro macro = 1;
}

message SetMacroResponse {
    oneof result {
        SetMacroOk ok = 1;
        SetMacroErrorCode err = 2;
    }
}

message SetMacroOk {
    Macro macro = 1;
    bool dirty = 2;
}

enum SetMacroErrorCode {
    SET_MACRO_ERR_OK = 0;
    SET_MACRO_ERR_GENERIC = 1;
    SET_MACRO_ERR_INVALID_SLOT = 2;
    SET_MACRO_ERR_INVALID_NAME = 3;
    SET_MACRO_ERR_INVALID_STEP = 4;
    SET_MACRO_ERR_INVALID_BEHAVIOR = 5;
    SET_MACRO_ERR_INVALID_PARAMETERS = 6;
    SET_MACRO_ERR_BUSY = 7;
    SET_MACRO_ERR_NO_SPACE = 8;
}

message SetTapMsRequest {
    uint32 tap_ms = 1;
}

message SetTapMsResponse {
    uint32 tap_ms = 1;
    bool dirty = 2;
}

message ResetMacroRequest {
    uint32 slot_index = 1;
}

message ResetMacroResponse {
    oneof result {
        SetMacroOk ok = 1;
        SetMacroErrorCode err = 2;
    }
}

message SaveChangesResponse {
    oneof result {
        bool ok = 1;
        SaveChangesErrorCode err = 2;
    }
}

enum SaveChangesErrorCode {
    SAVE_CHANGES_ERR_OK = 0;
    SAVE_CHANGES_ERR_GENERIC = 1;
    SAVE_CHANGES_ERR_NOT_SUPPORTED = 2;
    SAVE_CHANGES_ERR_NO_SPACE = 3;
}
